import { CustomerListTableTypes } from "@/types/dashboard/teacher/customer-management.types";

export const data: CustomerListTableTypes[] = [
  {
    customerId: "C001",
    name: "John Doe",
    address: "123 Green Street, Gulshan-2, Dhaka",
    customerType: "Residential",
    area: "Gulshan",
    contact01: "+880 1712 345678",
    lastServiceDate: "15-Sep-25",
    lastServiceItems: "Filter cleaning,\nTank inspection",
    nextServiceDate: "15-Oct-25",
    nextServiceItems: "Monthly maintenance,\nFilter replacement",
  },
  {
    customerId: "C002",
    name: "ABC Corporation",
    address: "456 Business Avenue, Dhanmondi, Dhaka",
    customerType: "Corporate",
    area: "Dhanmondi",
    contact01: "+880 1712 345678",
    lastServiceDate: "10-Sep-25",
    lastServiceItems: "System maintenance,\nWater quality test",
    nextServiceDate: "10-Oct-25",
    nextServiceItems: "Quarterly service,\nEquipment check",
  },
  {
    customerId: "C003",
    name: "Green Valley Apartments",
    address: "789 Residential Complex, Banani, Dhaka",
    customerType: "Rental",
    area: "Banani",
    contact01: "+880 1734 567890",
    lastServiceDate: "20-Sep-25",
    lastServiceItems: "Tank cleaning,\nPipe inspection",
    nextServiceDate: "20-Oct-25",
    nextServiceItems: "Bi-monthly service,\nFilter change",
  },
  {
    customerId: "C004",
    name: "Tech Solutions Ltd",
    address: "321 Innovation Drive, Uttara, Dhaka",
    customerType: "Corporate",
    area: "Uttara",
    contact01: "+880 1745 678901",
    lastServiceDate: "05-Sep-25",
    lastServiceItems: "Annual maintenance,\nFull system check",
    nextServiceDate: "05-Oct-25",
    nextServiceItems: "Comprehensive service,\nParts replacement",
  },
  {
    customerId: "C005",
    name: "Fatima Khan",
    address: "654 Housing Society, Mohammadpur, Dhaka",
    customerType: "Residential",
    area: "Mohammadpur",
    contact01: "+880 1756 789012",
    lastServiceDate: "12-Sep-25",
    lastServiceItems: "Filter replacement,\nWater testing",
    nextServiceDate: "12-Oct-25",
    nextServiceItems: "Monthly check-up,\nSystem cleaning",
  },
];
