export const AVAILABLE_TRAINING_TYPES = [
  "Self Defense",
  "Fitness Training",
  "Weight Loss Training",
  "Martial Arts",
  "Boxing / MMA",
  "Women Self Defense",
];

export const AVAILABLE_LOCATIONS = [
  "Khilkhet",
  "Kafrul",
  "Dhanmondi",
  "Mohammadpur",
  "Sutrapur",
  "Jatrabari",
  "Airport",
  "Gulshan",
  "Uttara",
  "Mugda",
  "Rupnagar",
  "Bhashantek",
  "Vatara",
  "Banani",
  "Wari",
  "Shajahanpur",
  "Sher E Bangla",
  "Mirpur",
  "Darus Salam",
  "Dakhshinkhan",
  "Uttarkhan",
  "Turag",
  "Cantonment",
  "Badda",
  "Pollobi",
  "Shah Ali",
  "Tejgaon Industrial Area",
  "Rampura",
  "Tejgaon",
  "Shobujbagh",
  "Kadamtali",
  "Chakbazar",
  "Kamrangirchar",
  "Kotowali",
  "Laalbagh",
  "Kalabagan",
  "Shahbagh",
  "Motijheel",
  "Khilgaon",
  "Hazaribagh",
  "Ramna",
  "Demra",
  "Paltan",
  "Bangshal",
  "New Market",
  "Shyampur",
  "Grandarea",
  "Adabor",
  "Other",
];

export const DAYS_OPTIONS = [
  "Saturday",
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
];
